services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - PORT=3000
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    build: ./backend
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    networks:
      - my-network
  
networks:
    my-network:
      driver: bridge
